rule all:
    input:
        "results/mass4l_combine_userlvl3.pdf"

rule scram:
    input:
        config["data"],
        config["code"]
    output:
        touch("results/scram_done.txt")
    container:
        "docker://docker.io/cmsopendata/cmssw_5_3_32"
    shell:
        "source /opt/cms/cmsset_default.sh "
        "&& scramv1 project CMSSW CMSSW_5_3_32 "
        "&& cd CMSSW_5_3_32/src "
        "&& eval `scramv1 runtime -sh` "
        "&& cp -r ../../code/HiggsExample20112012 . "
        "&& cd HiggsExample20112012/HiggsDemoAnalyzer "
        "&& scram b "
        "&& cd ../Level3 "
        "&& mkdir -p ../../../../results "

rule scram_Node_A:
    input:
        config["data"],
        config["code"]
    output:
        touch("results/scram_data_done.txt")
    container:
        "docker://docker.io/cmsopendata/cmssw_5_3_32"
    resources:
        kubernetes_queue="eosc-node-a"
    shell:
        "source /opt/cms/cmsset_default.sh "
        "&& scramv1 project CMSSW CMSSW_5_3_32 "
        "&& cd CMSSW_5_3_32/src "
        "&& eval `scramv1 runtime -sh` "
        "&& cp -r ../../code/HiggsExample20112012 . "
        "&& cd HiggsExample20112012/HiggsDemoAnalyzer "
        "&& scram b "
        "&& cd ../Level3 "
        "&& mkdir -p ../../../../results "

rule scram_Node_B:
    input:
        config["data"],
        config["code"]
    output:
        touch("results/scram_mc_done.txt")
    container:
        "docker://docker.io/cmsopendata/cmssw_5_3_32"
    resources:
        kubernetes_queue="eosc-node-b"
    shell:
        "source /opt/cms/cmsset_default.sh "
        "&& scramv1 project CMSSW CMSSW_5_3_32 "
        "&& cd CMSSW_5_3_32/src "
        "&& eval `scramv1 runtime -sh` "
        "&& cp -r ../../code/HiggsExample20112012 . "
        "&& cd HiggsExample20112012/HiggsDemoAnalyzer "
        "&& scram b "
        "&& cd ../Level3 "
        "&& mkdir -p ../../../../results "

rule analyse_data_Node_A:
    input:
        config["data"],
        config["code"],
        "results/scram_data_done.txt"
    output:
        "results/DoubleMuParked2012C_10000_Higgs.root"
    container:
        "docker://docker.io/cmsopendata/cmssw_5_3_32"
    resources:
        kubernetes_queue="eosc-node-a"
    shell:
        "source /opt/cms/cmsset_default.sh "
        "&& cd CMSSW_5_3_32/src "
        "&& eval `scramv1 runtime -sh` "
        "&& cd HiggsExample20112012/HiggsDemoAnalyzer "
        "&& cd ../Level3 "
        "&& cmsRun demoanalyzer_cfg_level3data.py"
        "&& mv ../../../../results/tmpDoubleMuParked2012C_10000_Higgs.root ../../../../results/DoubleMuParked2012C_10000_Higgs.root" 

rule analyse_mc_Node_B:
    input:
        config["data"],
        config["code"],
        "results/scram_mc_done.txt"
    output:
        "results/Higgs4L1file.root"
    container:
        "docker://docker.io/cmsopendata/cmssw_5_3_32"
    resources:
        kubernetes_queue="eosc-node-b"
    shell:
        "source /opt/cms/cmsset_default.sh "
        "&& cd CMSSW_5_3_32/src "
        "&& eval `scramv1 runtime -sh` "
        "&& cd HiggsExample20112012/HiggsDemoAnalyzer "
        "&& cd ../Level3 "
        "&& cmsRun demoanalyzer_cfg_level3MC.py"
        "&& mv ../../../../results/tmpHiggs4L1file.root ../../../../results/Higgs4L1file.root" 

rule make_plot:
    input:
        config["data"],
        config["code"],
        "results/scram_done.txt",
        "results/DoubleMuParked2012C_10000_Higgs.root",
        "results/Higgs4L1file.root"
    output:
        "results/mass4l_combine_userlvl3.pdf"
    container:
        "docker://docker.io/cmsopendata/cmssw_5_3_32"
    shell:
        "sleep 10 && source /opt/cms/cmsset_default.sh "
        "&& cd CMSSW_5_3_32/src "
        "&& eval `scramv1 runtime -sh` "
        "&& cd HiggsExample20112012/HiggsDemoAnalyzer "
        "&& cd ../Level3 "
        "&& root -b -l -q ./M4Lnormdatall_lvl3.cc"
